queue_rules:
  - name: shared_queue
    conditions:
      # Must write expected checks explicitly
      # Reference: https://docs.mergify.com/conditions/#validating-all-status-checks
      - check-success=check_license
      - check-success=golangci_lint


pull_request_rules:
  - name: put bug fix pr to queue with high priority
    conditions:
      - "#approved-reviews-by>=1"
      - label=bugfix
    actions:
      queue:
        name: shared_queue
        method: squash

  - name: put other pr to queue
    conditions:
      - "#approved-reviews-by>=1"
      - label!=bugfix
    actions:
      queue:
        name: shared_queue
        method: squash

  # if there is a conflict in a approved PR, ping the author.
  - name: ping author on conflicts
    conditions:
      - conflict
      - "#approved-reviews-by>=1"
    actions:
      comment:
        message: |
          This pull request has merge conflicts that must be resolved before it can be merged. @{{author}} please update it 🙏.
          Try `@mergify update` or update manually.

  - name: Welcome new contributor
    conditions:
      - author!=Mergify
    actions:
      comment:
        message: |
          Thanks for the contribution!
          Please review the labels and make any necessary changes.

  - name: Notify author on queue failure
    conditions:
      - 'check-failure=Queue: Embarked in merge train'
    actions:
      comment:
        message: >
          Hey @{{ author }}, this pull request failed to merge and has been
          dequeued from the merge train.  If you believe your PR failed in
          the merge train because of a flaky test, requeue it by commenting
          with `@mergifyio requeue`.
          More details can be found on the `Queue: Embarked in merge train`
          check-run.

  - name: ask owner to review  PR
    conditions:
      - author!=Mergify
    actions:
      request_reviews:
        users:
          - wanglei4687

  - name: label on Feature
    conditions:
      - body~=(?m)- \[(?i)x\] Feature
    actions:
      label:
        add:
          - feature

  - name: label on Bug Fix
    conditions:
      - body~=(?m)- \[(?i)x\] Bug
    actions:
      label:
        add:
          - bug

  - name: label on Improvement
    conditions:
      - body~=(?m)^- \[(?i)x\] Improvement
    actions:
      label:
        add:
          - improvement

  - name: label on CI
    conditions:
      - body~=(?m)^- \[(?i)x\] CI/CD
    actions:
      label:
        add:
          - ci/cd

  - name: label on Test
    conditions:
      - body~=(?m)^- \[(?i)x\] Test
    actions:
      label:
        add:
          - test

  - name: label on Build
    conditions:
      - body~=(?m)^- \[(?i)x\] Build
    actions:
      label:
        add:
          - build

  - name: label on Documentation
    conditions:
      - body~=(?m)^- \[(?i)x\] Documentation
    actions:
      label:
        add:
          - doc

  - name: label on Other
    conditions:
      - body~=(?m)- \[(?i)x\] Other
    actions:
      label:
        add:
          - other
